version: '3.8'

services:
  db:
    image: postgres:15
    container_name: database
    hostname: customer_chat_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatadmin
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_network

  app:
    image: customer_chat:latest
    container_name: chat
    hostname: customer_chat
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: "customer_chat_database"
      DB_PORT: '5432'
      DB_NAME: 'chatdb'
      DB_USER: 'chatadmin'
      DB_PASSWORD: 'secretpassword'
    volumes:
      - /var/log/chat:/chat/logs
    networks:
      - chat_network

volumes:
  postgres_data:
    driver: local

networks:
  chat_network:
    driver: bridge
