name: Customer Chat

on:
  push:
    branches: [ "develop", "feature_*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test-and-coverage:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies for functions
      - name: Install function dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r function/requirements.txt

      # Install dependencies for tests
      - name: Install test dependencies
        run: |
          pip install -r tests/requirements.txt

      # Run pytest with coverage
      - name: Run tests and generate coverage
        run: |
          pytest --cov=function --cov-report=html:documentation/.coverage --cov-report=term tests

      # Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: documentation/.coverage
